image: Visual Studio 2019

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - git submodule update --init --recursive

environment:
  app_version: "1.2"
  USE_RTOOLS: true
  R_ARCH: x64
  R_VERSION: "4.0.5"
  KEEP_VIGNETTES: true
  NOT_CRAN: true
  COVERALLS_TOKEN:
    secure: QItC20vr6rKHkiDVvsE+kHFL4GTS3bcsPw5KcWe+qipEIj1+ncKngsCoCNelNdtg

version: "$(app_version).{build}"

before_build:
  - rake "prepare_for_build[%APPVEYOR_BUILD_VERSION%]"

platform: x64

skip_commits:
  files:
    - "*.md"

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - develop

pull_requests:
  do_not_increment_build_number: true

before_test:
  - cinst pandoc
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl
  - Rscript -e "install.packages(c('ospsuite.utils','covr'), repos = 'http://cran.us.r-project.org', type='win.binary')"

test_script:
  - travis-tool.sh run_tests

after_test:
  - ps: copy tlf_*.tar.gz tlf.tar.gz
  - ps: copy tlf_*.zip tlf.zip

on_success:
  - Rscript -e "covr::codecov()"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*.tar.gz'
    name: Bits

  - path: '\*.zip'
    name: Bits

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyFEAs8X080yIO8g1FLt3tNfBN4OpeBnkgrXzf7AqNKV5561x7Coux3ByGrHmsL1sCo=
