# DO NOT CHANGE the "init" and "install" sections below

environment:
  USE_RTOOLS: true
  app_version: "0.1.0"
  R_ARCH: x64
  NOT_CRAN: true
  COVERALLS_TOKEN:
    secure: QItC20vr6rKHkiDVvsE+kHFL4GTS3bcsPw5KcWe+qipEIj1+ncKngsCoCNelNdtg

version: "$(app_version).{build}"

# Download script file from GitHub
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

platform: x64

skip_commits:
  files:
    - "*.md"

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
    - develop

pull_requests:
  do_not_increment_build_number: true

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl
  - Rscript -e "install.packages('covr', repos = 'http://cran.us.r-project.org')"

test_script:
  - travis-tool.sh run_tests

on_success:
  - Rscript -e "covr::codecov()"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyFEAs8X080yIO8g1FLt3tNfBN4OpeBnkgrXzf7AqNKV5561x7Coux3ByGrHmsL1sCo=
