name: Update release website
# The action is triggered only when a PR is merged
# Caution, a closed PR does not necessarily mean that it was merged
# A second assessment is required in the jobs
on:
  pull_request:
    branches:
      - main
    types:
      - closed

# The action needs permissions to update the branch
permissions:
  contents: write
          
jobs:
  update_release_website:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/CreateGitHubPagesForR.yml@main
    with:
      pkgdown_mode: 'release'
      extra_r_packages: 'github::Open-Systems-Pharmacology/OSPSuite.RUtils'
