name: Update release website
# The action is triggered only when a PR is merged
# Caution, a closed PR does not necessarily mean that it was merged
# A second assessment is required in the jobs
on:
  pull_request:
    branches:
      - main
    types:
      - closed
# The action needs permissions to update the branch
permissions:
  contents: write
env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  PKGDOWN_MODE: release
          
jobs:
  build:
  # Second assessment checking if PR was actually merged
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install required packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: github::Open-Systems-Pharmacology/OSPSuite.RUtils, any::pkgdown, local::.
          needs: website
      - name: Setup website to display only 2 digits
        run: |
          Rscript .github/workflows/pkgdown_setup.R
      - name: Build release site
        run: |
          options(yaml.eval.expr=TRUE)
          pkgdown::build_site(devel=TRUE, install=TRUE)
        shell: Rscript {0}
        # The project is then uploaded as an artifact named 'docs'.
      - name: Upload Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs

  deploy:
    concurrency: ci-${{ github.ref }}
    # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    needs: [build] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # The built project is downloaded into the 'docs' folder.
      - name: Download Artifacts 
        uses: actions/download-artifact@v1
        with:
          name: docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        # The deployment folder should match the name of the artifact.
        # Clean is false to prevent removing release site
        # only target folder of repo from gh-pages branch is updated
        with:
          folder: docs
          clean: false
          branch: gh-pages
          target-folder: docs
          token: ${{ secrets.GITHUB_TOKEN }}